### ISSUE TITLE
 get score from LTI provider

### ISSUE THREAD

**Issue by Muneera-Salah** [edx/xblock-lti-consumer#157]
Hi, I have an issue I searched a lot about reading score/grade from LTI to open-edx. but unfortunately, I did not get any answer How to get a score from the LTI provider? is there any other configuration? Anyone help me plz.

open-edx version: Hawthorn
I followed all these solutions:
- https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/lti_component.html
- https://blog.jazkarta.com/2015/02/08/adding-scorm-packages-to-open-edx-via-scormcloud-and-lti/
- https://discuss.openedx.org/t/how-can-i-enable-the-request-user-s-username-in-open-edx-admin-for-lti-configuration/1939

**Comment by Muneera-Salah** [comment]
`/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/lti_consumer/outcomes.py:169: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  error_message = "Request body XML parsing error: {} {}".format(ex.message, body)`

**Comment by nedbat** [comment]
GitHub issues might not work well as a support channel.  See Slack or Discourse: https://openedx.org/getting-help.
