### ISSUE TITLE
Request user’s username

### ISSUE THREAD

**Issue by benbro** [edx/xblock-lti-consumer#40]
How can I enable the "Request user’s username" in OpenEdx?

[Docs](https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/lti_component.html) says:

> To make this setting available, contact your edX partner manager.

**Comment by juniorojha** [comment]
Hi! Were you able to get the username sent to your LTI application?

**Comment by mumarkhan999** [comment]
@benbro Were you able to get the username?

**Comment by zheoreh** [comment]
@benbro why have you closed the issue?

**Comment by zheoreh** [comment]
I've enabled 'Request user's username' and 'Request user's email'. But I receive email and user name (lis_person_sourcedid field) but I expected full users' name (lis_person_name_full or lis_person_name_given or lis_person_name_family)
