### ISSUE TITLE
Request body XML parsing error: list index out of range

### ISSUE THREAD

**Issue by arkangel1611** [edx/xblock-lti-consumer#45]
Hi,

I was trying to return Grade from my LTI tool to OpenEdx, getting "Request body XML parsing error: list index out of range"

Can i get some help here ??

Request Body:
[Body.txt](https://github.com/edx/xblock-lti-consumer/files/2918731/Body.txt)

**Comment by nedbat** [comment]
See Slack or Discourse for help: https://openedx.org/getting-help.
