### ISSUE TITLE
If key has extra colons(:) in it.

### ISSUE THREAD

**Issue by sksankarraj** [edx/xblock-lti-consumer#71]
**Problem Statement:**

We had a situation where we faced an issue with parsing the LTI passports because of extra colons in them.

LTI passports are parsed by using colon(:) as a delimiter. We were trying to integrate LTI content from Rustici controller, the key format of the provider is `content:<unit-no>:<id>` the LTI passport will like 

`<content_id>:content:<unit-no>:<provider_id>:<secret_key>`

So this results to throwing unformatted Key exception.

PR for the FIX: #70

**Comment by stvstnfrd** [comment]
Fixed in #70
